// Blog posts embedded in full on a tool page via <ToolPageBottom/>. The tool
// page is the canonical home of that article; the standalone /blog/<slug> URL
// canonicalizes to it so the same text isn't indexed twice.
// Regenerate by grepping `ToolPageBottom slug=` if tools/articles move.
export const articleCanonicalTool: Record<string, string> = {
	"amilyar-real-property-tax-guide": "/amilyar-calculator",
	"architectural-fee-guide": "/architectural-fee-calculator",
	"bir-donors-tax-guide": "/bir-donors-tax-calculator",
	"bir-withholding-tax-guide": "/bir-withholding-tax-calculator",
	"bir-zonal-values-guide": "/zonal-value-calculator",
	"bpo-night-differential-philippines": "/bpo-night-differential-calculator",
	"budget-reverse-salary-calculator-guide": "/budget-calculator",
	"ched-scholarship-guide": "/ched-scholarship-calculator",
	"civil-service-reviewer-guide": "/civil-service-reviewer",
	"customs-brokerage-fee-guide": "/customs-brokerage-fee-calculator",
	"de-minimis-benefits-guide": "/de-minimis-tax-calculator",
	"dfa-age-requirements-guide": "/dfa-age-calculator",
	"digital-banks-philippines-interest-rates": "/digital-bank-calculator",
	"digital-ticket-guide": "/digital-ticket-generator",
	"dost-scholarship-stipend-guide": "/dost-scholarship-stipend-calculator",
	"estate-tax-guide": "/estate-tax-calculator",
	"final-pay-guide": "/final-pay-calculator",
	"food-costing-pricing-guide": "/food-cost-calculator",
	"freelance-hourly-rate-guide": "/freelance-rate-calculator",
	"gotrade-vs-ibkr-guide": "/gotrade-vs-ibkr-calculator",
	"gross-from-tax-computation-guide": "/gross-from-tax-calculator",
	"how-to-compute-13th-month-pay": "/13th-month-pay-calculator",
	"how-to-compute-gsis-pension": "/gsis-pension-calculator",
	"how-to-compute-gwa-college": "/gwa-calculator",
	"how-to-compute-sss-pension": "/sss-pension-calculator",
	"how-to-split-bills-properly": "/bill-splitter-calculator",
	"income-tax-brackets-2026": "/income-tax-calculator",
	"influencer-rate-guide": "/influencer-rate-calculator",
	"invoice-factoring-guide": "/invoice-factoring-calculator",
	"kasambahay-payroll-guide": "/kasambahay-payroll-calculator",
	"kasambahay-retirement-guide": "/kasambahay-retirement-calculator",
	"legal-contract-guide": "/promissory-note-generator",
	"lto-late-registration-penalty": "/lto-penalty-calculator",
	"lto-registration-renewal-guide": "/lto-registration-fee-calculator",
	"meralco-electric-bill-guide": "/electric-bill-calculator",
	"pagibig-contribution-table-2026": "/pagibig-calculator",
	"pagibig-foreclosed-property-roi": "/pagibig-foreclosed-roi-calculator",
	"pagibig-housing-loan-affordability-guide":
		"/pagibig-affordability-calculator",
	"pagibig-mp2-dividend-calculator": "/pagibig-mp2-calculator",
	"pdic-insurance-guide": "/pdic-insurance-calculator",
	"philhealth-contribution-table-2026": "/philhealth-calculator",
	"philhealth-late-contribution-guide":
		"/philhealth-late-contribution-calculator",
	"philippine-backpay-computation-guide": "/backpay-calculator",
	"philippine-car-loan-guide-bank-vs-dealer": "/car-loan-calculator",
	"philippine-fuel-cost-trip-calculator": "/fuel-cost-calculator",
	"philippine-holiday-pay-rules": "/holiday-calculator",
	"philippine-home-loan-guide-bank-comparison": "/home-loan-calculator",
	"philippine-latin-honors-guide": "/latin-honors-calculator",
	"philippine-overtime-holiday-pay-guide": "/overtime-pay-calculator",
	"philippine-separation-pay-guide": "/separation-pay-calculator",
	"philippine-tax-classification-guide": "/tax-optimizer-calculator",
	"philippine-toll-fees-guide": "/toll-calculator",
	"prc-board-exam-rating-guide": "/prc-board-exam-rating-calculator",
	"qpi-gpa-calculator-guide": "/qpi-gpa-calculator",
	"retail-treasury-bond-guide": "/retail-treasury-bond-calculator",
	"salary-tax-deductions-guide": "/salary-calculator",
	"shipping-logistics-guide": "/shipping-logistics-estimator",
	"shopee-lazada-seller-fees-explained": "/shopee-lazada-fee-calculator",
	"sss-contribution-table-2026": "/sss-contribution-calculator",
	"sss-maternity-benefit-guide": "/sss-maternity-benefit-calculator",
	"tax-refund-guide": "/tax-refund-calculator",
	"upwork-freelance-tax-guide": "/freelance-tax-calculator",
};
