export const toolCategories = [
	{
		category: "Finance & Salary",
		items: [
			{
				name: "Salary Net Pay Calculator",
				path: "/salary-calculator",
				desc: "Compute your take-home pay after SSS, PhilHealth, Pag-IBIG & Tax.",
				priority: 0.9,
			},
			{
				name: "BPO Night Differential Calculator",
				path: "/bpo-night-differential-calculator",
				desc: "Compute your 10% night shift differential pay based on Philippine BPO hours.",
				priority: 0.8,
			},
			{
				name: "Overtime & Holiday Pay Calculator",
				path: "/overtime-pay-calculator",
				desc: "Calculate DOLE-compliant overtime and premium pay for rest days and holidays.",
				priority: 0.8,
			},
			{
				name: "Budget & Reverse Salary Calculator",
				path: "/budget-calculator",
				desc: "List your expenses and find out what gross salary you should ask for.",
				priority: 0.8,
			},
			{
				name: "SSS Contribution Calculator",
				path: "/sss-contribution-calculator",
				desc: "See your exact SSS breakdown (EE/ER/EC/MPF) based on the 2026 table.",
				priority: 0.9,
			},
			{
				name: "SSS Retirement Pension Calculator",
				path: "/sss-pension-calculator",
				desc: "Estimate your monthly lifetime pension based on your AMSC and Credited Years of Service.",
				priority: 0.9,
			},
			{
				name: "GSIS Retirement Pension Calculator",
				path: "/gsis-pension-calculator",
				desc: "Calculate your GSIS Basic Monthly Pension (BMP) based on RA 8291.",
				priority: 0.9,
			},
			{
				name: "SSS Maternity Benefit Calculator",
				path: "/sss-maternity-calculator",
				desc: "Calculate your 105-day Expanded Maternity Leave cash benefit based on your SSS contributions.",
				priority: 0.9,
			},
			{
				name: "PhilHealth Premium Calculator",
				path: "/philhealth-calculator",
				desc: "Calculate your exact monthly PhilHealth premium based on the latest 5% UHC rate.",
				priority: 0.9,
			},
			{
				name: "Income Tax Calculator (BIR)",
				path: "/income-tax-calculator",
				desc: "Calculate your annual and monthly income tax using TRAIN law brackets.",
				priority: 0.9,
			},
			{
				name: "Gross from Tax Calculator",
				path: "/gross-from-tax-calculator",
				desc: "Estimate your equivalent gross salary directly from a target withholding tax amount.",
				priority: 0.8,
			},
			{
				name: "13th Month Calculator",
				path: "/13th-month-pay-calculator",
				desc: "Compute your prorated 13th month and tax exemptions.",
				priority: 0.8,
			},
			{
				name: "Final Pay (Backpay) Calculator",
				path: "/backpay-calculator",
				desc: "Estimate your final pay, prorated 13th month, and leave conversions after resigning.",
				priority: 0.8,
			},
			{
				name: "Separation Pay Calculator",
				path: "/separation-pay-calculator",
				desc: "Calculate your DOLE separation pay for redundancy, retrenchment, and other terminations.",
				priority: 0.8,
			},
			{
				name: "Upwork & Freelance Tax Calculator",
				path: "/freelance-tax-calculator",
				desc: "Calculate your net PHP after Upwork fees, forex spread, and 8% BIR tax.",
				priority: 0.9,
			},
			{
				name: "Freelance Hourly Rate Calculator",
				path: "/freelance-rate-calculator",
				desc: "Find out exactly how much to charge clients per hour to hit your net income goals.",
				priority: 0.9,
			},
			{
				name: "8% vs Graduated Tax Optimizer",
				path: "/tax-optimizer-calculator",
				desc: "Find out if 8% Flat Rate, OSD, or Itemized deductions will save you more money.",
				priority: 0.9,
			},
			{
				name: "Digital Bank Interest Calculator",
				path: "/digital-bank-calculator",
				desc: "Compare high-yield savings (Maya, SeaBank, Gotyme) and calculate net interest after 20% tax.",
				priority: 0.9,
			},
			{
				name: "TikTok, Shopee & Lazada Fee Calculator",
				path: "/shopee-lazada-fee-calculator",
				desc: "Calculate exact seller deductions (Commission, FSS, TikTok fees) and net payout.",
				priority: 0.9,
			},
			{
				name: "Food Cost & Pricing Calculator",
				path: "/food-cost-calculator",
				desc: "Calculate your recipe costs and find the perfect selling price with a target profit margin.",
				priority: 0.9,
			},
			{
				name: "De Minimis Tax Optimization Estimator",
				path: "/de-minimis-tax-calculator",
				desc: "Maximize your tax-free allowances and bonuses based on BIR regulations.",
				priority: 0.9,
			},
			{
				name: "LTO Annual Registration Fee Estimator",
				path: "/lto-registration-fee-calculator",
				desc: "Calculate your Motor Vehicle User's Charge (MVUC) and late renewal penalties.",
				priority: 0.9,
			},
			{
				name: "SSS Maternity Benefit Estimator",
				path: "/sss-maternity-benefit-calculator",
				desc: "Calculate your expected SSS Maternity Cash Benefit based on the Expanded Maternity Leave Law.",
				priority: 0.9,
			},
			{
				name: "BIR Donor's Tax Cumulative Calculator",
				path: "/bir-donors-tax-calculator",
				desc: "Calculate your cumulative donor's tax liability based on the BIR TRAIN Law (RA 10963).",
				priority: 0.9,
			},
			{
				name: "Architectural Fee Calculator (UAP SPP 202)",
				path: "/architectural-fee-calculator",
				desc: "Calculate minimum basic fees for architectural design based on UAP SPP 202.",
				priority: 0.9,
			},
			{
				name: "Standard Customs Brokerage Fee Calculator",
				path: "/customs-brokerage-fee-calculator",
				desc: "Calculate minimum professional fees for customs brokers under CAO No. 1-2001.",
				priority: 0.9,
			},
			{
				name: "Philippine Influencer & Talent Rate Calculator",
				path: "/influencer-rate-calculator",
				desc: "Calculate standard creator rates based on engagement metrics.",
				priority: 0.9,
			},
			{
				name: "Pro-Rated 13th Month & Final Pay Calculator",
				path: "/final-pay-calculator",
				desc: "Calculate final pay, prorated 13th-month bonus, and unused SIL conversion.",
				priority: 0.9,
			},
			{
				name: "Year-End Tax Refund Estimator",
				path: "/tax-refund-calculator",
				desc: "Calculate potential tax refunds by reconciling YTD withheld taxes against actual tax due.",
				priority: 0.9,
			},
			{
				name: "Kasambahay Monthly Contribution & Payroll Calculator",
				path: "/kasambahay-payroll-calculator",
				desc: "Compute SSS, PhilHealth, and Pag-IBIG contributions for household employees.",
				priority: 0.9,
			},
			{
				name: "Batas Kasambahay Statutory Retirement Pay Calculator",
				path: "/kasambahay-retirement-calculator",
				desc: "Calculate retirement pay for domestic workers under Article 302 of the Labor Code.",
				priority: 0.9,
			},
			{
				name: "Philippine Estate Tax Calculator",
				path: "/estate-tax-calculator",
				desc: "Calculate the 6% flat estate tax under the TRAIN Law.",
				priority: 0.9,
			},
			{
				name: "GoTrade vs IBKR Wise Fee Calculator",
				path: "/gotrade-vs-ibkr-calculator",
				desc: "Compare FX spreads and trading fees to find the break-even deposit amount.",
				priority: 0.9,
			},
			{
				name: "PDIC Deposit Insurance Estimator",
				path: "/pdic-insurance-calculator",
				desc: "Calculate your maximum PDIC deposit insurance coverage.",
				priority: 0.9,
			},
			{
				name: "PhilHealth Late Contribution Penalty Estimator",
				path: "/philhealth-late-contribution-calculator",
				desc: "Estimate interest penalties on missed PhilHealth premium payments.",
				priority: 0.9,
			},
			{
				name: "Retail Treasury Bond (RTB) Yield Estimator",
				path: "/retail-treasury-bond-calculator",
				desc: "Calculate net quarterly payouts and total yield on Philippine RTBs.",
				priority: 0.9,
			},
			{
				name: "Local Shipping & Logistics Rate Estimator",
				path: "/shipping-logistics-estimator",
				desc: "Calculate standard delivery costs for local MSME e-commerce.",
				priority: 0.9,
			},
			{
				name: "PH Crypto Exchange Spread Calculator",
				path: "/crypto-spread-calculator",
				desc: "Compare hidden spreads when buying crypto on local apps.",
				priority: 0.9,
			},
			{
				name: "P2P Crypto Cash-Out Calculator",
				path: "/crypto-p2p-cashout-calculator",
				desc: "Calculate exact PHP earnings when selling USDT via P2P.",
				priority: 0.9,
			},
			{
				name: "BIR Crypto Tax Calculator",
				path: "/crypto-tax-calculator",
				desc: "Estimate income tax liability on crypto profits under BIR rules.",
				priority: 0.9,
			},
			{
				name: "Civil Service Exam Reviewer",
				path: "/civil-service-reviewer",
				desc: "Offline-capable mock exams for the Philippine CSE.",
				priority: 0.9,
			},
			{
				name: "Legal Contract Generator",
				path: "/legal-contract-generator",
				desc: "Generate standard Philippine legal documents securely.",
				priority: 0.9,
			},
			{
				name: "Invoice Factoring & Discount Calculator",
				path: "/invoice-factoring-calculator",
				desc: "Calculate NPV, APR, and ROI when selling unpaid invoices.",
				priority: 0.9,
			},
			{
				name: "Digital Ticketing QR Generator",
				path: "/digital-ticket-generator",
				desc: "Generate secure QR code tickets without a database.",
				priority: 0.9,
			},
			{
				name: "Expanded Withholding Tax (EWT) Calculator",
				path: "/bir-withholding-tax-calculator",
				desc: "Calculate BIR Form 2307 deductions for freelancers, professionals, and suppliers.",
				priority: 0.9,
			},
			{
				name: "Electric Bill Estimator",
				path: "/electric-bill-calculator",
				desc: "Estimate your Meralco bill based on appliance usage and current rates.",
				priority: 0.7,
			},
		],
	},
	{
		category: "Loans, Housing & Real Estate",
		items: [
			{
				name: "Car Loan & Amortization Calculator",
				path: "/car-loan-calculator",
				desc: "Compare bank vs in-house auto loans, down payment, and monthly amortization.",
				priority: 0.9,
			},
			{
				name: "Motorcycle Loan Calculator (Hulugan)",
				path: "/motorcycle-loan-calculator",
				desc: "Calculate your exact monthly amortization, total interest, and hidden costs for in-house dealer financing.",
				priority: 0.9,
			},
			{
				name: "Pag-IBIG MP2 Dividend Calculator",
				path: "/pagibig-mp2-calculator",
				desc: "Calculate your tax-free earnings from the Pag-IBIG MP2 Savings Program over 5 years.",
				priority: 0.9,
			},
			{
				name: "Home Loan & Mortgage Calculator",
				path: "/home-loan-calculator",
				desc: "Compute monthly bank home loan payments, interest rates, and loan terms.",
				priority: 0.9,
			},
			{
				name: "Amilyar (Property Tax) Calculator",
				path: "/amilyar-calculator",
				desc: "Estimate your annual Philippine Real Property Tax (RPT) and SEF.",
				priority: 0.7,
			},
			{
				name: "Pag-IBIG / MP2 Calculator",
				path: "/pagibig-calculator",
				desc: "Estimate your MP2 savings dividends and standard housing loan amortization.",
				priority: 0.8,
			},
			{
				name: "Pag-IBIG Foreclosed Property ROI Calculator",
				path: "/pagibig-foreclosed-roi-calculator",
				desc: "Calculate rental yield and flipping ROI for Acquired Assets.",
				priority: 0.9,
			},
			{
				name: "Pag-IBIG Housing Loan Affordability",
				path: "/pagibig-affordability-calculator",
				desc: "Find out exactly how much housing loan you can afford based on your salary and age.",
				priority: 0.9,
			},
		],
	},
	{
		category: "Education & Students",
		items: [
			{
				name: "UP/PUP GWA Calculator",
				path: "/gwa-calculator",
				desc: "Calculate your General Weighted Average (1.0-5.0) and predict target grades.",
				priority: 0.8,
			},
			{
				name: "PRC Board Exam Rating Calculator",
				path: "/prc-board-exam-rating-calculator",
				desc: "Calculate your general average and passing status for NLE, CE, MTLE, and CPALE.",
				priority: 0.9,
			},
			{
				name: "Latin Honors Calculator",
				path: "/latin-honors-calculator",
				desc: "Check if your GWA qualifies for Cum Laude at UP, PUP, UST, Ateneo, or DLSU.",
				priority: 0.9,
			},
			{
				name: "DOST-SEI Scholarship Stipend Calculator",
				path: "/dost-scholarship-stipend-calculator",
				desc: "Calculate your exact yearly DOST scholarship benefits and stipend breakdown.",
				priority: 0.9,
			},
			{
				name: "CHED Scholarship Calculator",
				path: "/ched-scholarship-calculator",
				desc: "Calculate your exact annual benefits for CHED Merit (CMSP) and Tulong Dunong (TDP).",
				priority: 0.9,
			},
			{
				name: "QPI / GPA Calculator (4.0 Scale)",
				path: "/qpi-gpa-calculator",
				desc: "Calculate your Ateneo QPI or DLSU CGPA with the 4.0 grading scale.",
				priority: 0.8,
			},
		],
	},
	{
		category: "Creative & Media",
		items: [
			{
				name: "ID Photo Maker",
				path: "/id-photo-maker",
				desc: "Create 2x2, 1x1, and passport photos from your selfies for free.",
				priority: 0.6,
			},
		],
	},
	{
		category: "Utilities",
		items: [
			{
				name: "Fuel Cost Calculator",
				path: "/fuel-cost-calculator",
				desc: "Estimate your road trip gas expenses and easily divide costs for ambagan.",
				priority: 0.6,
			},
			{
				name: "LTO Penalty Calculator",
				path: "/lto-penalty-calculator",
				desc: "Check exactly how much your MVUC fine is for late vehicle registration.",
				priority: 0.7,
			},
			{
				name: "Expressway Toll Calculator",
				path: "/toll-calculator",
				desc: "Lookup TRB-approved toll fees for Skyway, SLEX, NLEX, and TPLEX.",
				priority: 0.8,
			},
			{
				name: "Holiday & Overtime Pay",
				path: "/holiday-calculator",
				desc: "See the 2026 calendar and calculate your special/regular holiday pay.",
				priority: 0.7,
			},
			{
				name: "Exact Age Calculator (DFA & PRC)",
				path: "/dfa-age-calculator",
				desc: "Calculate your exact age in years, months, and days for passports and board exams.",
				priority: 0.8,
			},
			{
				name: "GCash & Maya Bill Splitter",
				path: "/bill-splitter-calculator",
				desc: "Split restaurant bills fairly including VAT and service charges.",
				priority: 0.8,
			},
		],
	},
	{
		category: "Gaming & Esports Utilities",
		items: [
			{
				name: "MLBB Diamond Top-Up Optimizer",
				path: "/mlbb-diamond-calculator",
				desc: "Find the best PHP-to-Diamond ratio across top-up sites.",
				priority: 0.9,
			},
			{
				name: "MLBB Win Rate Calculator",
				path: "/mlbb-winrate-calculator",
				desc: "Calculate consecutive wins needed for your target win rate.",
				priority: 0.9,
			},
			{
				name: "CODM Lucky Draw Estimator",
				path: "/codm-lucky-draw-calculator",
				desc: "Calculate the total CP and PHP cost of a Lucky Draw.",
				priority: 0.9,
			},
			{
				name: "Genshin Pity & Primogem Calculator",
				path: "/genshin-pity-calculator",
				desc: "Calculate pulls and PHP needed to guarantee a 5-star character.",
				priority: 0.9,
			}
		],
	},
];

// Flattened list of all tool paths for easy iteration
export const allToolPaths = toolCategories.flatMap((category) =>
	category.items.map((item) => item.path),
);
