export const toolCategories = [
	{
		category: "Finance & Salary",
		items: [
			{
				name: "Salary Net Pay Calculator",
				path: "/salary-calculator",
				desc: "Compute your take-home pay after SSS, PhilHealth, Pag-IBIG & Tax.",
				tags: [
					"net pay",
					"take home",
					"sweldo",
					"suweldo",
					"payroll",
					"gross",
					"deductions",
					"monthly pay",
					"sss",
					"philhealth",
					"tax",
				],
				priority: 0.9,
			},
			{
				name: "BPO Night Differential Calculator",
				path: "/bpo-night-differential-calculator",
				desc: "Compute your 10% night shift differential pay based on Philippine BPO hours.",
				tags: [
					"night differential",
					"nightdiff",
					"night shift",
					"graveyard",
					"bpo",
					"call center",
					"premium pay",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "Overtime & Holiday Pay Calculator",
				path: "/overtime-pay-calculator",
				desc: "Calculate DOLE-compliant overtime and premium pay for rest days and holidays.",
				tags: [
					"overtime",
					"ot pay",
					"holiday pay",
					"rest day",
					"premium pay",
					"dole",
					"sobra oras",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "Budget & Reverse Salary Calculator",
				path: "/budget-calculator",
				desc: "List your expenses and find out what gross salary you should ask for.",
				tags: [
					"budget",
					"reverse salary",
					"gastos",
					"expenses",
					"monthly budget",
					"gross salary",
					"take home",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "SSS Contribution Calculator",
				path: "/sss-contribution-calculator",
				desc: "See your exact SSS breakdown (EE/ER/EC/MPF) based on the 2026 table.",
				tags: [
					"sss",
					"social security",
					"contribution",
					"kontribusyon",
					"hulog",
					"msc",
					"mpf",
					"wisp",
				],
				priority: 0.9,
			},
			{
				name: "SSS Retirement Pension Calculator",
				path: "/sss-pension-calculator",
				desc: "Estimate your monthly lifetime pension based on your AMSC and Credited Years of Service.",
				tags: [
					"sss",
					"pension",
					"retirement",
					"pensyon",
					"retiro",
					"amsc",
					"social security",
					"monthly pension",
				],
				priority: 0.9,
			},
			{
				name: "GSIS Retirement Pension Calculator",
				path: "/gsis-pension-calculator",
				desc: "Calculate your GSIS Basic Monthly Pension (BMP) based on RA 8291.",
				tags: [
					"gsis",
					"pension",
					"retirement",
					"pensyon",
					"retiro",
					"government employee",
					"bmp",
					"ra 8291",
				],
				priority: 0.9,
			},
			{
				name: "SSS Maternity Benefit Calculator",
				path: "/sss-maternity-benefit-calculator",
				desc: "Calculate your 105-day Expanded Maternity Leave cash benefit based on your SSS contributions.",
				tags: [
					"maternity",
					"maternity benefit",
					"maternity leave",
					"105 days",
					"buntis",
					"panganganak",
					"sss",
					"expanded maternity",
				],
				priority: 0.9,
			},
			{
				name: "PhilHealth Premium Calculator",
				path: "/philhealth-calculator",
				desc: "Calculate your exact monthly PhilHealth premium based on the latest 5% UHC rate.",
				tags: [
					"philhealth",
					"premium",
					"contribution",
					"kontribusyon",
					"uhc",
					"health insurance",
					"hulog",
					"5 percent",
				],
				priority: 0.9,
			},
			{
				name: "Income Tax Calculator (BIR)",
				path: "/income-tax-calculator",
				desc: "Calculate your annual and monthly income tax using TRAIN law brackets.",
				tags: [
					"income tax",
					"bir",
					"train law",
					"withholding tax",
					"buwis",
					"tax bracket",
					"annual tax",
					"monthly tax",
				],
				priority: 0.9,
			},
			{
				name: "Gross from Tax Calculator",
				path: "/gross-from-tax-calculator",
				desc: "Estimate your equivalent gross salary directly from a target withholding tax amount.",
				tags: [
					"gross from tax",
					"reverse tax",
					"gross up",
					"withholding tax",
					"buwis",
					"gross salary",
					"bir",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "13th Month Calculator",
				path: "/13th-month-pay-calculator",
				desc: "Compute your prorated 13th month and tax exemptions.",
				tags: [
					"13th month",
					"13th month pay",
					"ikatlong buwan",
					"bonus",
					"christmas bonus",
					"prorated",
					"dole",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "Final Pay (Backpay) Calculator",
				path: "/backpay-calculator",
				desc: "Estimate your final pay, prorated 13th month, and leave conversions after resigning.",
				tags: [
					"backpay",
					"final pay",
					"last pay",
					"resignation",
					"resign",
					"leave conversion",
					"separation",
					"sweldo",
				],
				priority: 0.8,
			},
			{
				name: "Separation Pay Calculator",
				path: "/separation-pay-calculator",
				desc: "Calculate your DOLE separation pay for redundancy, retrenchment, and other terminations.",
				tags: [
					"separation pay",
					"redundancy",
					"retrenchment",
					"termination",
					"layoff",
					"tanggal sa trabaho",
					"severance",
					"dole",
				],
				priority: 0.8,
			},
			{
				name: "Upwork & Freelance Tax Calculator",
				path: "/freelance-tax-calculator",
				desc: "Calculate your net PHP after Upwork fees, forex spread, and 8% BIR tax.",
				tags: [
					"freelance",
					"freelancer",
					"upwork",
					"8 percent tax",
					"bir",
					"forex",
					"online worker",
					"self employed",
				],
				priority: 0.9,
			},
			{
				name: "Freelance Hourly Rate Calculator",
				path: "/freelance-rate-calculator",
				desc: "Find out exactly how much to charge clients per hour to hit your net income goals.",
				tags: [
					"freelance rate",
					"hourly rate",
					"per hour",
					"how much to charge",
					"pricing",
					"rate",
					"freelancer",
					"client",
				],
				priority: 0.9,
			},
			{
				name: "8% vs Graduated Tax Optimizer",
				path: "/tax-optimizer-calculator",
				desc: "Find out if 8% Flat Rate, OSD, or Itemized deductions will save you more money.",
				tags: [
					"tax optimizer",
					"8 percent vs graduated",
					"osd",
					"itemized",
					"deduction",
					"bir",
					"save tax",
					"self employed",
				],
				priority: 0.9,
			},
			{
				name: "Digital Bank Interest Calculator",
				path: "/digital-bank-calculator",
				desc: "Compare high-yield savings (Maya, SeaBank, Gotyme) and calculate net interest after 20% tax.",
				tags: [
					"digital bank",
					"interest",
					"savings",
					"maya",
					"seabank",
					"gotyme",
					"high yield",
					"ipon",
				],
				priority: 0.9,
			},
			{
				name: "TikTok, Shopee & Lazada Fee Calculator",
				path: "/shopee-lazada-fee-calculator",
				desc: "Calculate exact seller deductions (Commission, FSS, TikTok fees) and net payout.",
				tags: [
					"shopee",
					"lazada",
					"tiktok",
					"seller fee",
					"commission",
					"ecommerce",
					"online selling",
					"payout",
				],
				priority: 0.9,
			},
			{
				name: "Food Cost & Pricing Calculator",
				path: "/food-cost-calculator",
				desc: "Calculate your recipe costs and find the perfect selling price with a target profit margin.",
				tags: [
					"food cost",
					"recipe cost",
					"pricing",
					"menu",
					"restaurant",
					"profit margin",
					"presyo",
					"selling price",
				],
				priority: 0.9,
			},
			{
				name: "De Minimis Tax Optimization Estimator",
				path: "/de-minimis-tax-calculator",
				desc: "Maximize your tax-free allowances and bonuses based on BIR regulations.",
				tags: [
					"de minimis",
					"tax free",
					"allowance",
					"bonus",
					"benefits",
					"bir",
					"non taxable",
					"exempt",
				],
				priority: 0.9,
			},
			{
				name: "LTO Annual Registration Fee Estimator",
				path: "/lto-registration-fee-calculator",
				desc: "Calculate your Motor Vehicle User's Charge (MVUC) and late renewal penalties.",
				tags: [
					"lto",
					"registration fee",
					"mvuc",
					"renewal",
					"rehistro",
					"motor vehicle",
					"late penalty",
					"car registration",
				],
				priority: 0.9,
			},
			{
				name: "BIR Donor's Tax Cumulative Calculator",
				path: "/bir-donors-tax-calculator",
				desc: "Calculate your cumulative donor's tax liability based on the BIR TRAIN Law (RA 10963).",
				tags: [
					"donors tax",
					"donation",
					"gift tax",
					"bir",
					"train law",
					"regalo",
					"donate",
					"ra 10963",
				],
				priority: 0.9,
			},
			{
				name: "Architectural Fee Calculator (UAP SPP 202)",
				path: "/architectural-fee-calculator",
				desc: "Calculate minimum basic fees for architectural design based on UAP SPP 202.",
				tags: [
					"architect",
					"architectural fee",
					"uap",
					"spp 202",
					"design fee",
					"professional fee",
					"building",
					"arkitekto",
				],
				priority: 0.9,
			},
			{
				name: "Standard Customs Brokerage Fee Calculator",
				path: "/customs-brokerage-fee-calculator",
				desc: "Calculate minimum professional fees for customs brokers under CAO No. 1-2001.",
				tags: [
					"customs",
					"brokerage fee",
					"customs broker",
					"import",
					"cao",
					"professional fee",
					"clearance",
					"shipping",
				],
				priority: 0.9,
			},
			{
				name: "Philippine Influencer & Talent Rate Calculator",
				path: "/influencer-rate-calculator",
				desc: "Calculate standard creator rates based on engagement metrics.",
				tags: [
					"influencer",
					"content creator",
					"talent rate",
					"engagement",
					"social media",
					"sponsorship",
					"vlogger",
					"rate card",
				],
				priority: 0.9,
			},
			{
				name: "Pro-Rated 13th Month & Final Pay Calculator",
				path: "/final-pay-calculator",
				desc: "Calculate final pay, prorated 13th-month bonus, and unused SIL conversion.",
				tags: [
					"final pay",
					"last pay",
					"backpay",
					"prorated 13th month",
					"sil",
					"resignation",
					"separation",
					"sweldo",
				],
				priority: 0.9,
			},
			{
				name: "Year-End Tax Refund Estimator",
				path: "/tax-refund-calculator",
				desc: "Calculate potential tax refunds by reconciling YTD withheld taxes against actual tax due.",
				tags: [
					"tax refund",
					"year end",
					"refund",
					"withholding tax",
					"overpaid tax",
					"bir",
					"sobrang buwis",
					"ytd",
				],
				priority: 0.9,
			},
			{
				name: "Kasambahay Monthly Contribution & Payroll Calculator",
				path: "/kasambahay-payroll-calculator",
				desc: "Compute SSS, PhilHealth, and Pag-IBIG contributions for household employees.",
				tags: [
					"kasambahay",
					"household helper",
					"payroll",
					"katulong",
					"yaya",
					"domestic worker",
					"sss",
					"philhealth",
				],
				priority: 0.9,
			},
			{
				name: "Batas Kasambahay Statutory Retirement Pay Calculator",
				path: "/kasambahay-retirement-calculator",
				desc: "Calculate retirement pay for domestic workers under Article 302 of the Labor Code.",
				tags: [
					"kasambahay",
					"retirement pay",
					"katulong",
					"domestic worker",
					"retiro",
					"labor code",
					"household helper",
					"batas kasambahay",
				],
				priority: 0.9,
			},
			{
				name: "Philippine Estate Tax Calculator",
				path: "/estate-tax-calculator",
				desc: "Calculate the 6% flat estate tax under the TRAIN Law.",
				tags: [
					"estate tax",
					"inheritance",
					"mana",
					"train law",
					"death tax",
					"namatay",
					"heirs",
					"bir",
				],
				priority: 0.9,
			},
			{
				name: "GoTrade vs IBKR Wise Fee Calculator",
				path: "/gotrade-vs-ibkr-calculator",
				desc: "Compare FX spreads and trading fees to find the break-even deposit amount.",
				tags: [
					"gotrade",
					"ibkr",
					"interactive brokers",
					"wise",
					"forex",
					"stocks",
					"trading fees",
					"us stocks",
				],
				priority: 0.9,
			},
			{
				name: "PDIC Deposit Insurance Estimator",
				path: "/pdic-insurance-calculator",
				desc: "Calculate your maximum PDIC deposit insurance coverage.",
				tags: [
					"pdic",
					"deposit insurance",
					"bank",
					"savings",
					"coverage",
					"insured deposit",
					"bank failure",
					"protected",
				],
				priority: 0.9,
			},
			{
				name: "PhilHealth Late Contribution Penalty Estimator",
				path: "/philhealth-late-contribution-calculator",
				desc: "Estimate interest penalties on missed PhilHealth premium payments.",
				tags: [
					"philhealth",
					"late payment",
					"penalty",
					"interest",
					"missed",
					"arrears",
					"contribution",
					"hulog",
				],
				priority: 0.9,
			},
			{
				name: "Retail Treasury Bond (RTB) Yield Estimator",
				path: "/retail-treasury-bond-calculator",
				desc: "Calculate net quarterly payouts and total yield on Philippine RTBs.",
				tags: [
					"rtb",
					"treasury bond",
					"bonds",
					"yield",
					"government bond",
					"investment",
					"coupon",
					"interest",
				],
				priority: 0.9,
			},
			{
				name: "Local Shipping & Logistics Rate Estimator",
				path: "/shipping-logistics-estimator",
				desc: "Calculate standard delivery costs for local MSME e-commerce.",
				tags: [
					"shipping",
					"logistics",
					"delivery",
					"courier",
					"padala",
					"freight",
					"msme",
					"ecommerce",
				],
				priority: 0.9,
			},

			{
				name: "Civil Service Exam Reviewer",
				path: "/civil-service-reviewer",
				desc: "Offline-capable mock exams for the Philippine CSE.",
				tags: [
					"civil service",
					"cse",
					"reviewer",
					"mock exam",
					"csc",
					"government exam",
					"pasada",
					"professional exam",
				],
				priority: 0.9,
			},
			{
				name: "Legal Contract Generator",
				path: "/legal-contract-generator",
				desc: "Generate standard Philippine legal documents securely.",
				tags: [
					"legal contract",
					"document",
					"agreement",
					"kontrata",
					"template",
					"affidavit",
					"generator",
					"legal form",
				],
				priority: 0.9,
			},
			{
				name: "Invoice Factoring & Discount Calculator",
				path: "/invoice-factoring-calculator",
				desc: "Calculate NPV, APR, and ROI when selling unpaid invoices.",
				tags: [
					"invoice factoring",
					"discount",
					"npv",
					"apr",
					"roi",
					"receivables",
					"cash flow",
					"financing",
				],
				priority: 0.9,
			},
			{
				name: "Digital Ticketing QR Generator",
				path: "/digital-ticket-generator",
				desc: "Generate secure QR code tickets without a database.",
				tags: [
					"ticket",
					"qr code",
					"event",
					"qr ticket",
					"generator",
					"entrance",
					"registration",
					"tiket",
				],
				priority: 0.9,
			},
			{
				name: "Expanded Withholding Tax (EWT) Calculator",
				path: "/bir-withholding-tax-calculator",
				desc: "Calculate BIR Form 2307 deductions for freelancers, professionals, and suppliers.",
				tags: [
					"ewt",
					"expanded withholding tax",
					"bir",
					"form 2307",
					"withholding",
					"freelancer",
					"supplier",
					"professional",
				],
				priority: 0.9,
			},
			{
				name: "Electric Bill Estimator",
				path: "/electric-bill-calculator",
				desc: "Estimate your Meralco bill based on appliance usage and current rates.",
				tags: [
					"electric bill",
					"meralco",
					"kuryente",
					"electricity",
					"kwh",
					"appliance",
					"power bill",
					"consumption",
				],
				priority: 0.7,
			},
		],
	},
	{
		category: "Loans, Housing & Real Estate",
		items: [
			{
				name: "BIR Zonal Value & Real Estate Tax Engine",
				path: "/zonal-value-calculator",
				desc: "Calculate Capital Gains Tax and DST instantly using our massive database of street-level BIR Zonal Values.",
				tags: [
					"zonal value",
					"bir",
					"capital gains tax",
					"cgt",
					"dst",
					"real estate",
					"halaga ng lupa",
					"property tax",
				],
				priority: 0.95,
			},
			{
				name: "Car Loan & Amortization Calculator",
				path: "/car-loan-calculator",
				desc: "Compare bank vs in-house auto loans, down payment, and monthly amortization.",
				tags: [
					"car loan",
					"auto loan",
					"amortization",
					"down payment",
					"kotse",
					"financing",
					"monthly amortization",
					"vehicle loan",
				],
				priority: 0.9,
			},
			{
				name: "Motorcycle Loan Calculator (Hulugan)",
				path: "/motorcycle-loan-calculator",
				desc: "Calculate your exact monthly amortization, total interest, and hidden costs for in-house dealer financing.",
				tags: [
					"motorcycle loan",
					"hulugan",
					"motor",
					"amortization",
					"in-house financing",
					"down payment",
					"motorsiklo",
					"installment",
				],
				priority: 0.9,
			},
			{
				name: "Pag-IBIG MP2 Dividend Calculator",
				path: "/pagibig-mp2-calculator",
				desc: "Calculate your tax-free earnings from the Pag-IBIG MP2 Savings Program over 5 years.",
				tags: [
					"pag-ibig",
					"mp2",
					"dividend",
					"savings",
					"modified pag-ibig 2",
					"ipon",
					"tax free",
					"hdmf",
				],
				priority: 0.9,
			},
			{
				name: "Home Loan & Mortgage Calculator",
				path: "/home-loan-calculator",
				desc: "Compute monthly bank home loan payments, interest rates, and loan terms.",
				tags: [
					"home loan",
					"mortgage",
					"housing loan",
					"amortization",
					"bahay",
					"interest rate",
					"monthly payment",
					"loan term",
				],
				priority: 0.9,
			},
			{
				name: "Amilyar (Property Tax) Calculator",
				path: "/amilyar-calculator",
				desc: "Estimate your annual Philippine Real Property Tax (RPT) and SEF.",
				tags: [
					"amilyar",
					"real property tax",
					"rpt",
					"buwis sa lupa",
					"property tax",
					"sef",
					"lupa",
					"bahay",
				],
				priority: 0.7,
			},
			{
				name: "Pag-IBIG / MP2 Calculator",
				path: "/pagibig-calculator",
				desc: "Estimate your MP2 savings dividends and standard housing loan amortization.",
				tags: [
					"pag-ibig",
					"mp2",
					"housing loan",
					"dividend",
					"savings",
					"amortization",
					"ipon",
					"hdmf",
				],
				priority: 0.8,
			},
			{
				name: "Pag-IBIG Foreclosed Property ROI Calculator",
				path: "/pagibig-foreclosed-roi-calculator",
				desc: "Calculate rental yield and flipping ROI for Acquired Assets.",
				tags: [
					"pag-ibig",
					"foreclosed",
					"acquired assets",
					"roi",
					"rental yield",
					"flipping",
					"subasta",
					"property",
				],
				priority: 0.9,
			},
			{
				name: "Pag-IBIG Housing Loan Affordability",
				path: "/pagibig-affordability-calculator",
				desc: "Find out exactly how much housing loan you can afford based on your salary and age.",
				tags: [
					"pag-ibig",
					"housing loan",
					"affordability",
					"loanable amount",
					"bahay",
					"kaya bayaran",
					"eligibility",
					"sweldo",
				],
				priority: 0.9,
			},
		],
	},
	{
		category: "Education & Students",
		items: [
			{
				name: "UP/PUP GWA Calculator",
				path: "/gwa-calculator",
				desc: "Calculate your General Weighted Average (1.0-5.0) and predict target grades.",
				tags: [
					"gwa",
					"general weighted average",
					"grade",
					"up",
					"pup",
					"grades",
					"average",
					"marka",
				],
				priority: 0.8,
			},
			{
				name: "PRC Board Exam Rating Calculator",
				path: "/prc-board-exam-rating-calculator",
				desc: "Calculate your general average and passing status for NLE, CE, MTLE, and CPALE.",
				tags: [
					"prc",
					"board exam",
					"rating",
					"nle",
					"cpale",
					"general average",
					"licensure",
					"pasa",
				],
				priority: 0.9,
			},
			{
				name: "Latin Honors Calculator",
				path: "/latin-honors-calculator",
				desc: "Check if your GWA qualifies for Cum Laude at UP, PUP, UST, Ateneo, or DLSU.",
				tags: [
					"latin honors",
					"cum laude",
					"magna cum laude",
					"summa cum laude",
					"gwa",
					"honors",
					"graduation",
					"dlsu",
				],
				priority: 0.9,
			},
			{
				name: "DOST-SEI Scholarship Stipend Calculator",
				path: "/dost-scholarship-stipend-calculator",
				desc: "Calculate your exact yearly DOST scholarship benefits and stipend breakdown.",
				tags: [
					"dost",
					"scholarship",
					"stipend",
					"dost-sei",
					"allowance",
					"scholar",
					"merit",
					"benefits",
				],
				priority: 0.9,
			},
			{
				name: "CHED Scholarship Calculator",
				path: "/ched-scholarship-calculator",
				desc: "Calculate your exact annual benefits for CHED Merit (CMSP) and Tulong Dunong (TDP).",
				tags: [
					"ched",
					"scholarship",
					"cmsp",
					"tulong dunong",
					"tdp",
					"merit",
					"grant",
					"scholar",
				],
				priority: 0.9,
			},
			{
				name: "QPI / GPA Calculator (4.0 Scale)",
				path: "/qpi-gpa-calculator",
				desc: "Calculate your Ateneo QPI or DLSU CGPA with the 4.0 grading scale.",
				tags: [
					"qpi",
					"gpa",
					"4.0 scale",
					"cgpa",
					"ateneo",
					"dlsu",
					"grade point",
					"average",
				],
				priority: 0.8,
			},
		],
	},
	{
		category: "Creative & Media",
		items: [
			{
				name: "ID Photo Maker",
				path: "/id-photo-maker",
				desc: "Create 2x2, 1x1, and passport photos from your selfies for free.",
				tags: [
					"id photo",
					"2x2",
					"1x1",
					"passport photo",
					"selfie",
					"larawan",
					"id picture",
					"resize photo",
				],
				priority: 0.6,
			},
		],
	},
	{
		category: "Utilities",
		items: [
			{
				name: "Fuel Cost Calculator",
				path: "/fuel-cost-calculator",
				desc: "Estimate your road trip gas expenses and easily divide costs for ambagan.",
				tags: [
					"fuel cost",
					"gas",
					"gasoline",
					"road trip",
					"krudo",
					"mileage",
					"ambagan",
					"diesel",
				],
				priority: 0.6,
			},
			{
				name: "LTO Penalty Calculator",
				path: "/lto-penalty-calculator",
				desc: "Check exactly how much your MVUC fine is for late vehicle registration.",
				tags: [
					"lto",
					"penalty",
					"fine",
					"mvuc",
					"late registration",
					"multa",
					"renewal",
					"vehicle",
				],
				priority: 0.7,
			},
			{
				name: "Expressway Toll Calculator",
				path: "/toll-calculator",
				desc: "Lookup TRB-approved toll fees for Skyway, SLEX, NLEX, and TPLEX.",
				tags: [
					"toll",
					"expressway",
					"skyway",
					"slex",
					"nlex",
					"tplex",
					"toll fee",
					"trb",
				],
				priority: 0.8,
			},
			{
				name: "Holiday & Overtime Pay",
				path: "/holiday-calculator",
				desc: "See the 2026 calendar and calculate your special/regular holiday pay.",
				tags: [
					"holiday pay",
					"regular holiday",
					"special holiday",
					"overtime",
					"piyesta",
					"2026 holidays",
					"dole",
					"pista opisyal",
				],
				priority: 0.7,
			},
			{
				name: "Exact Age Calculator (DFA & PRC)",
				path: "/dfa-age-calculator",
				desc: "Calculate your exact age in years, months, and days for passports and board exams.",
				tags: [
					"age calculator",
					"exact age",
					"dfa",
					"passport",
					"birthday",
					"edad",
					"date of birth",
					"board exam",
				],
				priority: 0.8,
			},
			{
				name: "GCash & Maya Bill Splitter",
				path: "/bill-splitter-calculator",
				desc: "Split restaurant bills fairly including VAT and service charges.",
				tags: [
					"bill splitter",
					"split bill",
					"gcash",
					"maya",
					"vat",
					"service charge",
					"hatian",
					"restaurant",
				],
				priority: 0.8,
			},
		],
	},
];

// Flattened list of all tool paths for easy iteration
export const allToolPaths = toolCategories.flatMap((category) =>
	category.items.map((item) => item.path),
);

export const LOCALES = ["en", "tl", "ceb"];

/**
 * Resolve the tool path key from a pathname: strips the locale prefix and keeps
 * only the first segment, so nested routes (e.g. the zonal-value drilldown)
 * still map back to their tool entry.
 */
export function toolKeyFromPathname(pathname: string): string {
	const parts = pathname.split("/").filter(Boolean);
	if (parts.length && LOCALES.includes(parts[0])) parts.shift();
	return `/${parts[0] ?? ""}`;
}
